== 給湯設備

=== タブの下の表示項目
なし

=== タブ下の説明

見出し::
給湯設備

説明::
====
衛生的で快適な住生活をおくる上で、給湯設備は不可欠なものとなっています。住宅におけるエネルギー消費のうち、給湯に費やされる割合はたいへん大きく、給湯設備を計画する上で省エネルギーに配慮することは非常に重要です。
====

=== 環境条件
なし

=== 入力

[[DHW_system]]
==== 給湯システム

説明::
====
給湯設備の有無、浴室等の有無を選択します。 +
ここで、浴室等とは、浴室やその他浴槽または身体の清浄を目的とした設備を有する室のことをいいます。
====

===== a. 給湯設備・浴室等の有無の選択 [選択入力]

選択肢::
* 給湯設備がある(浴室等がある) [D]
* 給湯設備がある(浴室等がない)
* 給湯設備がない

[[DHW_heat_source_type]]
==== 給湯熱源機

表示条件::
<<DHW_system>> "a. 給湯設備・浴室等の有無の選択" = "給湯設備がある(浴室等がある)" or
<<DHW_system>> "a. 給湯設備・浴室等の有無の選択" = "給湯設備がある(浴室等がない)"

===== a. 熱源機の分類 [選択入力]

表示条件::
<<DHW_system>> "a. 給湯設備・浴室等の有無の選択" = "給湯設備がある(浴室等がある)" or
<<DHW_system>> "a. 給湯設備・浴室等の有無の選択" = "給湯設備がある(浴室等がない)"

説明::
====
温水暖房用の温水供給を兼ねる場合は「給湯・温水暖房一体型」を、コージェネレーション設備を設置している場合は「コージェネレーションを使用する」選択して下さい。コージェネレーション設備の種類は、タブ「コージェネ」で選択できます。 +
評価時点で給湯機を設置しない場合は「給湯設備機器を設置しない」を、また選択肢にない給湯機を設置する場合は、「その他の給湯設備機器」を選択し、その名称も入力して下さい。
====

選択肢::
* 給湯専用型 [D]
* 給湯・温水暖房一体型
* コージェネレーションを使用する
* その他の熱源機
* 熱源機を設置しない

===== b. 熱源機(給湯専用型)の種類 [選択入力]

表示条件::
"a. 熱源機の分類" = "給湯専用型"

選択肢::
* ガス従来型給湯機 [D]
* ガス潜熱回収型給湯機
* 石油従来型給湯機
* 石油潜熱回収型給湯機
* 電気ヒーター温水器
* 電気ヒートポンプ給湯機(CO~2~冷媒)(太陽熱利用給湯設備を使用しないもの)
* 電気ヒートポンプ・ガス併用型給湯機

===== c. 効率の入力 [選択入力]

表示条件::
"b. 熱源機(給湯専用型)の種類" = "ガス従来型給湯機"

説明::
====
ガス従来型給湯機の効率は、エネルギー消費効率またはモード熱効率で表されます。 +
エネルギー消費効率とは、「エネルギーの使用の合理化に関する法律」に基づく「特定機器の性能の向上に関する製造事業者等の判断の基準等」（ガス温水機器）に定義される「エネルギー消費効率」のことです。ただし、給湯温水暖房機でふろ機能の種類が「給湯単機能」あるいは「ふろ給湯機（追焚なし）」の場合は、JIS S 2109 による「（瞬間湯沸器の）熱効率」に基づき測定された値になります。 +
モード熱効率とは、JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値です。
====

選択肢::
* 入力しない [D]
* 効率(エネルギー消費効率)を入力することにより省エネルギー効果を評価する
* 効率(モード熱効率)を入力することにより省エネルギー効果を評価する

===== d. エネルギー消費効率 [数値入力]

表示条件::
"c. 効率の入力" = "効率(エネルギー消費効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=70.4 単位=%

===== e. モード熱効率 [数値入力]

表示条件::
"c. 効率の入力" = "効率(モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=70.4 単位=%

===== f. 効率の入力 [選択入力]

表示条件::
"b. 熱源機(給湯専用型)の種類" = "ガス潜熱回収型給湯機"

説明::
====
ガス潜熱回収型給湯機の効率は、エネルギー消費効率またはモード熱効率で表されます。 +
エネルギー消費効率とは、「エネルギーの使用の合理化に関する法律」に基づく「特定機器の性能の向上に関する製造事業者等の判断の基準等」（ガス温水機器）に定義される「エネルギー消費効率」のことです。ただし、給湯温水暖房機でふろ機能の種類が「給湯単機能」あるいは「ふろ給湯機（追焚なし）」の場合は、JIS S 2109 による「（瞬間湯沸器の）熱効率」に基づき測定された値になります。 +
モード熱効率とは、JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値です。
====

選択肢::
* 入力しない [D]
* 効率(エネルギー消費効率)を入力することにより省エネルギー効果を評価する
* 効率(モード熱効率)を入力することにより省エネルギー効果を評価する

===== g. エネルギー消費効率 [数値入力]

表示条件::
"f. 効率の入力" = "効率(エネルギー消費効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=70.4 単位=%

===== h. モード熱効率 [数値入力]

表示条件::
"f. 効率の入力" = "効率(モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=83.6 単位=%

===== i. 効率の入力 [選択入力]

表示条件::
"b. 熱源機(給湯専用型)の種類" = "石油従来型給湯機"

説明::
====
石油従来型給湯機の効率は、熱効率またはモード熱効率で表されます。 +
熱効率とは、JIS S 3031（石油燃焼機器の試験方法通則）の連続給湯効率試験方法あるいは湯沸効率試験方法に基づく「熱効率」の値です。 +
モード熱効率とは、評価対象機器の JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に基づくモード熱効率の値です。
====

選択肢::
* 入力しない [D]
* 効率(熱効率)を入力することにより省エネルギー効果を評価する
* 効率(モード熱効率)を入力することにより省エネルギー効果を評価する

===== j. 熱効率 [数値入力]

表示条件::
"i. 効率の入力" = "効率(熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=77.9 単位=%

===== k. モード熱効率 [数値入力]

表示条件::
"i. 効率の入力" = "効率(モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=77.9 単位=%

===== l. 効率の入力 [選択入力]

表示条件::
"b. 熱源機(給湯専用型)の種類" = "石油潜熱回収型給湯機"

説明::
====
石油潜熱回収型給湯機の効率は、熱効率またはモード熱効率で表されます。 +
熱効率とは、JIS S 3031（石油燃焼機器の試験方法通則）の連続給湯効率試験方法あるいは湯沸効率試験方法に基づく「熱効率」の値です。 +
モード熱効率とは、評価対象機器の JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に基づくモード熱効率の値です。
====

選択肢::
* 入力しない [D]
* 効率(熱効率)を入力することにより省エネルギー効果を評価する
* 効率(モード熱効率)を入力することにより省エネルギー効果を評価する

===== m. 熱効率 [数値入力]

表示条件::
"l. 効率の入力" = "効率(熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=77.9 単位=%

===== n. モード熱効率 [数値入力]

表示条件::
"l. 効率の入力" = "効率(モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=81.9 単位=%

===== o. 効率の入力 [選択入力]

表示条件::
"b. 熱源機(給湯専用型)の種類" = "電気ヒートポンプ給湯機(CO~2~冷媒)(太陽熱利用給湯設備を使用しないもの)"

選択肢::
* 入力しない [D]
* JIS効率を入力することにより省エネルギー効果を評価する
* M1スタンダードに基づくJIS相当効率を入力することにより省エネルギー効果を評価する(認定機種のみ)

===== p. JIS効率 [数値入力]

表示条件::
"o. 効率の入力" = "JIS効率を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=5.0, 小数点=1, 規定値=2.7

===== q. 機種名 [テキスト入力]

表示条件::
"o. 効率の入力" = "M1スタンダードに基づくJIS相当効率を入力することにより省エネルギー効果を評価する(認定機種のみ)"

===== r. M1スタンダードに基づくJIS相当効率 [数値入力]

表示条件::
"o. 効率の入力" = "M1スタンダードに基づくJIS相当効率を入力することにより省エネルギー効果を評価する(認定機種のみ)"

入力規則::
最小値=0.00, 最大値=5.00, 小数点=2, 規定値=3.60

===== s. 品番の指定 [選択入力]

表示条件::
"b. 熱源機(給湯専用型)の種類" = "電気ヒートポンプ・ガス併用型給湯機"

選択肢::
* 入力する [D]
* 入力しない

===== t. 品番 [テキスト入力]

表示条件::
"s. 品番の指定" = "入力する"

===== u. 冷媒の種類とタンク容量

表示条件::
"s. 品番の指定" = "入力しない"

選択肢::
* フロン系冷媒でタンク容量(小) [D]
* フロン系冷媒でタンク容量(大)
* プロパン系冷媒

===== v. 熱源機(給湯・温水暖房一体型)の種類 [選択入力]

表示条件::
"a. 熱源機の分類" = "給湯・温水暖房一体型"

選択肢::
* ガス従来型給湯温水暖房機 [D]
* ガス潜熱回収型温水暖房給湯機
* 石油従来型給湯温水暖房機
* 石油潜熱回収型給湯温水暖房機
* 電気ヒーター給湯温水暖房器
* 電気ヒートポンプ・ガス併用型給湯温水暖房機

===== w. 効率の入力 [選択入力]

表示条件::
"v. 熱源機(給湯・温水暖房一体型)の種類" = "ガス従来型給湯温水暖房機"

説明::
====
ガス従来型給湯温水暖房機には暖房部と給湯部があります。 +
ガス従来型給湯温水暖房機の給湯部の効率は、エネルギー消費効率またはモード熱効率で表されます。 +
エネルギー消費効率とは、「エネルギーの使用の合理化に関する法律」に基づく「特定機器の性能の向上に関する製造事業者等の判断の基準等」（ガス温水機器）に定義される「エネルギー消費効率」のことです。ただし、給湯温水暖房機でふろ機能の種類が「給湯単機能」あるいは「ふろ給湯機（追焚なし）」の場合は、JIS S 2109 による「（瞬間湯沸器の）熱効率」に基づき測定された値になります。 +
モード熱効率とは、JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値です。 +
ガス従来型給湯温水暖房機の暖房部の効率は、熱効率で表されます。 +
熱効率とは、JIS S 2112（家庭用ガス温水熱源機）に定められた測定方法による「エネルギー消費効率（％）」（熱効率（％））の値です。
====

選択肢::
* 入力しない [D]
* 効率(暖房部:熱効率 給湯部:エネルギー消費効率)を入力することにより省エネルギー効果を評価する
* 効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する

===== x. 暖房部熱効率 [数値入力]

表示条件::
"w. 効率の入力" = "効率(暖房部:熱効率 給湯部:エネルギー消費効率)を入力することにより省エネルギー効果を評価する" or +
"w. 効率の入力" = "効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=81.0 単位=%

===== y. 給湯部エネルギー消費効率 [数値入力]

表示条件::
"w. 効率の入力" = "効率(暖房部:熱効率 給湯部:エネルギー消費効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=70.4 単位=%

===== z. 給湯部モード熱効率 [数値入力]

表示条件::
"w. 効率の入力" = "効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=70.4 単位=%

===== aa. 効率の入力 [選択入力]

表示条件::
"v. 熱源機(給湯・温水暖房一体型)の種類" = "ガス潜熱回収型給湯温水暖房機"

説明::
====
ガス潜熱回収型給湯温水暖房機には暖房部と給湯部があります。 +
ガス潜熱回収型給湯温水暖房機の給湯部の効率は、エネルギー消費効率またはモード熱効率で表されます。 +
エネルギー消費効率とは、「エネルギーの使用の合理化に関する法律」に基づく「特定機器の性能の向上に関する製造事業者等の判断の基準等」（ガス温水機器）に定義される「エネルギー消費効率」のことです。ただし、給湯温水暖房機でふろ機能の種類が「給湯単機能」あるいは「ふろ給湯機（追焚なし）」の場合は、JIS S 2109 による「（瞬間湯沸器の）熱効率」に基づき測定された値になります。 +
モード熱効率とは、JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値です。 +
ガス潜熱回収型給湯温水暖房機の暖房部の効率は、熱効率で表されます。 +
熱効率とは、JIS S 2112（家庭用ガス温水熱源機）に定められた測定方法による「エネルギー消費効率（％）」（熱効率（％））の値です。
====

選択肢::
* 入力しない [D]
* 効率(暖房部:熱効率 給湯部:エネルギー消費効率)を入力することにより省エネルギー効果を評価する
* 効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する

===== ab. 暖房部熱効率 [数値入力]

表示条件::
"aa. 効率の入力" = "効率(暖房部:熱効率 給湯部:エネルギー消費効率)を入力することにより省エネルギー効果を評価する" or +
"aa. 効率の入力" = "効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=87.0 単位=%

===== ac. 給湯部エネルギー消費効率 [数値入力]

表示条件::
"aa. 効率の入力" = "効率(暖房部:熱効率 給湯部:エネルギー消費効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=83.6 単位=%

===== ad. モード熱効率 [数値入力]

表示条件::
"aa. 効率の入力" = "効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=83.6 単位=%

===== ae. 効率の入力 [選択入力]

表示条件::
"v. 熱源機(給湯・温水暖房一体型)の種類" = "石油従来型給湯温水暖房機"

説明::
====
石油従来型給湯温水暖房機には暖房部と給湯部があります。 +
石油従来型給湯温水暖房機の給湯部の効率は、熱効率またはモード熱効率で表されます。 +
熱効率とは、JIS S 3031（石油燃焼機器の試験方法通則）の連続給湯効率試験方法あるいは湯沸効率試験方法に基づく「熱効率」の値です。 +
モード熱効率とは、評価対象機器の JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に基づくモード熱効率の値です。
石油従来型給湯温水暖房機の暖房部の効率は、熱効率で表されます。
熱効率とは、JIS S 3031 （石油燃焼機器の試験方法通則）に定められた測定方法による「エネルギー消費効率（%）」（熱効率（%））の値です。
====

選択肢::
* 入力しない [D]
* 効率(暖房部:熱効率 給湯部:熱効率)を入力することにより省エネルギー効果を評価する
* 効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する

===== af. 暖房部熱効率 [数値入力]

表示条件::
"ae. 効率の入力" = "効率(暖房部:熱効率 給湯部:熱効率)を入力することにより省エネルギー効果を評価する" or +
"ae. 効率の入力" = "効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=82.0 単位=%

===== ag. 給湯部熱効率 [数値入力]

表示条件::
"ae. 効率の入力" = "効率(暖房部:熱効率 給湯部:熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=77.9 単位=%

===== ah. 給湯部モード熱効率 [数値入力]

表示条件::
"ae. 効率の入力" = "効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=77.9 単位=%

===== ai. 効率の入力 [選択入力]

表示条件::
"v. 熱源機(給湯・温水暖房一体型)の種類" = "石油潜熱回収型給湯温水暖房機"

説明::
====
石油潜熱回収型給湯温水暖房機には暖房部と給湯部があります。 +
石油潜熱回収型給湯温水暖房機の給湯部の効率は、熱効率またはモード熱効率で表されます。 +
熱効率とは、JIS S 3031（石油燃焼機器の試験方法通則）の連続給湯効率試験方法あるいは湯沸効率試験方法に基づく「熱効率」の値です。 +
モード熱効率とは、評価対象機器の JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に基づくモード熱効率の値です。
石油潜熱回収型給湯温水暖房機の暖房部の効率は、熱効率で表されます。
熱効率とは、JIS S 3031 （石油燃焼機器の試験方法通則）に定められた測定方法による「エネルギー消費効率（%）」（熱効率（%））の値です。
====

選択肢::
* 入力しない [D]
* 効率(暖房部:熱効率 給湯部:熱効率)を入力することにより省エネルギー効果を評価する
* 効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する

===== aj. 暖房部熱効率 [数値入力]

表示条件::
"ai. 効率の入力" = "効率(暖房部:熱効率 給湯部:熱効率)を入力することにより省エネルギー効果を評価する" or +
"ai. 効率の入力" = "効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=82.0 単位=%

===== ak. 給湯部熱効率 [数値入力]

表示条件::
"ai. 効率の入力" = "効率(暖房部:熱効率 給湯部:熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=77.9 単位=%

===== al. 給湯部モード熱効率 [数値入力]

表示条件::
"ai. 効率の入力" = "効率(暖房部:熱効率 給湯部:モード熱効率)を入力することにより省エネルギー効果を評価する"

入力規則::
最小値=0.0, 最大値=100.0, 小数点=1, 規定値=77.9 単位=%

===== am. 熱源構成 [選択入力]

表示条件::
"v. 熱源機(給湯・温水暖房一体型)の種類" = "電気ヒートポンプ・ガス併用型給湯温水暖房機"

選択肢::
* 暖房部：電気ヒートポンプ・ガス、給湯部：ガス
* 暖房部：電気ヒートポンプ・ガス、給湯部：電気ヒートポンプ・ガス
* 暖房部：ガス、給湯部：電気ヒートポンプ・ガス [D]

===== an. タンクユニットの設置場所 [選択入力]

表示条件::
"am. 熱源構成" = "暖房部：電気ヒートポンプ・ガス、給湯部：ガス"

選択肢::
* 屋内に設置する
* 屋外に設置する [D]

===== ao. 品番の指定 [選択入力]

表示条件::
"v. 熱源機(給湯・温水暖房一体型)の種類" = "電気ヒートポンプ・ガス併用型給湯温水暖房機"

選択肢::
* 入力する [D]
* 入力しない

===== ap. 品番 [テキスト入力]

表示条件::
"ao. 品番の指定" = "入力する"

===== aq. 冷媒の種類とタンク容量 [選択入力]

表示条件::
"ao. 品番の指定" = "入力しない"

選択肢::
* フロン系冷媒でタンク容量(小) [D]
* フロン系冷媒でタンク容量(大)
* プロパン系冷媒

==== ar. ふろ機能の種類 [選択入力]

表示条件::
<<DHW_heat_source_type>> "a. 熱源機の分類" = "コージェネレーションを使用する" or
<<DHW_heat_source_type>> "a. 熱源機の分類" = "その他の熱源機" or
"b. 熱源機(給湯専用型)の種類" = "ガス従来型給湯機" or
"b. 熱源機(給湯専用型)の種類" = "ガス潜熱回収型給湯機" or
"b. 熱源機(給湯専用型)の種類" = "石油従来型給湯機" or
"b. 熱源機(給湯専用型)の種類" = "石油潜熱回収型給湯機" or
"b. 熱源機(給湯専用型)の種類" = "電気ヒーター温水器" or
"b. 熱源機(給湯専用型)の種類" = "電気ヒートポンプ給湯機(CO~2~冷媒)(太陽熱利用給湯設備を使用しないもの)" or
"v. 熱源機(給湯・温水暖房一体型)の種類" = "ガス従来型給湯温水暖房機" or
"v. 熱源機(給湯・温水暖房一体型)の種類" = "ガス潜熱回収型給湯温水暖房機" or
"v. 熱源機(給湯・温水暖房一体型)の種類" = "石油従来型給湯温水暖房機" or
"v. 熱源機(給湯・温水暖房一体型)の種類" = "石油潜熱回収型給湯温水暖房機" or
"v. 熱源機(給湯・温水暖房一体型)の種類" = "電気ヒーター給湯温水暖房機" or

選択肢::
* 給湯単機能
* ふろ給湯機(追焚なし)
* ふろ給湯機(追焚あり) [D]

[[DHW_piping]]
==== 配管

===== a. 配管の方式 [選択入力]

選択肢::
* 先分岐方式 [D]
* ヘッダー方式

===== b. ヘッダー分岐後の配管径 [選択入力]

表示条件::
"a. 配管の方式" = "ヘッダー方式"

選択肢::
* ヘッダー分岐後のすべての配管径が13A以下
* ヘッダー分岐後のいずれかの配管径が13Aより大きい [D]

[[DHW_tap]]
==== 水栓

===== a. 台所水栓 [選択入力]

選択肢::
* 2バルブ水栓
* 2バルブ水栓以外のその他の水栓

===== b. 手元止水機能 [選択入力]

表示条件::
"a. 台所水栓" = "2バルブ水栓以外のその他の水栓"

選択肢::
* 採用しない [D]
* 採用する

===== c. 水優先吐水機能

表示条件::
"a. 台所水栓" = "2バルブ水栓以外のその他の水栓"

選択肢::
* 採用しない [D]
* 採用する

===== d. 浴室シャワー水栓 [選択入力]

選択肢::
* 2バルブ水栓 [D]
* 2バルブ水栓以外のその他の水栓

===== e. 手元止水機能 [選択入力]

表示条件::
"d. 浴室シャワー水栓" = "2バルブ水栓以外のその他の水栓"

選択肢::
* 採用しない [D]
* 採用する

===== f. 小流量吐水機能

表示条件::
"d. 浴室シャワー水栓" = "2バルブ水栓以外のその他の水栓"

選択肢::
* 採用しない [D]
* 採用する

===== g. 洗面水栓 [選択入力]

選択肢::
* 2バルブ水栓
* 2バルブ水栓以外のその他の水栓 [D]

===== h. 水優先吐水機能 [選択入力]

表示条件::
"g. 洗面水栓" = "2バルブ水栓以外のその他の水栓"

選択肢::
* 採用しない [D]
* 採用する

[[DHW_batutub]]
==== 浴槽

===== a. 浴槽の保温措置 [選択入力]

選択肢::
* 措置しない [D]
* 措置する

===== b. 浴槽の節湯 [選択入力]

選択肢::
* 大きさを入力しない [D]
* 大きさを入力する

===== c. 浴槽の大きさ [数値入力]

表示条件::
"b. 浴槽の節湯" = "大きさを入力する"

入力規則::
最小値=0, 最大値=300, 小数点=0, 規定値=170 単位=L
