== 太陽熱給湯

=== タブの下の表示項目

目標レベル A (給湯エネルギー削減率B%程度)

=== タブ下の説明

見出し::
太陽熱給湯

説明::

====
住宅におけるエネルギー消費のうち、給湯に費やされる割合はたいへん大きく、自然エネルギーである太陽熱を利用した給湯システムの導入は、省エネルギーの観点からは有効な手段となります。
====

=== 環境条件

NOTE: <<GL_anual_solar_revision>> の内容を埋め込み

=== 入力

[[SP_install]]
==== 太陽熱給湯の採用について [選択入力]

選択肢::
* 採用する
* 採用しない [規定値]

[[SP_type]]
==== 太陽熱給湯設備の種類 [選択入力]

表示条件::
「<<SP_install>>」=「採用する」

説明::

====
太陽熱給湯装置は、「太陽熱温水器」と「ソーラーシステム」に分類されます。太陽熱温水器は日射で水を直接加熱する方式で、簡便でイニシャルコストが低いメリットがありますが、冬期は凍結防止のため水抜きをする必要があるので集熱はできません。ソーラーシステムは不凍液を循環させて集熱する方式で、冬期も集熱が可能ですが、設備が複雑になりイニシャルコストは高くなります。また、集熱中は不凍液の循環ポンプが常に電力を消費するため、消費電力は大きくなります。([underline]#太陽熱温水器とソーラーシステムの構成と特徴#)
====

【ポップアップ:太陽熱温水器とソーラーシステムの構成と特徴】::
====
表 太陽熱温水器とソーラーシステムの構成と特徴
// ガイドライン p.119 の表をはりつけること。
====

選択肢::
* 太陽熱温水器(太陽熱給湯1) [規定値]
* ソーラーシステム(太陽熱給湯2)

[[SP_solor_water_heater]]
==== 太陽熱温水器(太陽熱給湯1)

表示条件::
「<<SP_type>>」=「太陽熱温水器(太陽熱給湯1)」

===== a. 面積の入力方法 [選択入力]

表示条件::
「<<SP_type>>」=「太陽熱温水器(太陽熱給湯1)」

説明::

====
太陽熱温水器の面積の定義は2種類あります。 +
有効集熱面積は、 ISO 9488「Solar energy - Vocabulary」の 8.6 節「aperture area」に規定される方法により算出する値です。
集熱部総面積又は集熱貯湯部総面積は、JIS A4111「太陽熱温水器」に規定されています。
====

選択肢::
* 集熱部総面積又は集熱貯湯部総面積を入力する [規定値]
* 有効集熱面積を入力する

===== b. 集熱部面積又は集熱貯湯部総面積 [数値入力]

表示条件::
「a. 面積の入力方法」=「集熱部面積又は集熱貯湯部総面積を入力する」

入力規則::
最小値=0.0, 最大値=99.9, 小数点=1, 規定値=0.0, 単位=m^2^

===== c. 有効集熱面積 [数値入力]

表示条件::
「a. 面積の入力方法」=「有効集熱面積を入力する」

入力規則::
最小値=0.0, 最大値=99.9, 小数点=1, 規定値=0.0, 単位=m^2^

===== d. 集熱部の設置方位角 [選択入力]

表示条件::
「<<SP_type>>」=「太陽熱温水器(太陽熱給湯1)」

選択肢::
* 真南から東および西へ15度未満 [規定値]
* 真南から東へ15度以上45度未満
* 真南から東へ45度以上75度未満
* 真南から東へ75度以上105度未満
* 真南から東へ105度以上135度未満
* 真南から東へ135度以上165度未満
* 真南から東および西へ165度以上真北まで
* 真南から西へ135度以上165度未満
* 真南から西へ105度以上135度未満
* 真南から西へ75度以上105度未満
* 真南から西へ45度以上75度未満
* 真南から西へ15度以上45度未満

===== e. 集熱部の設置傾斜角 [選択入力]

表示条件::
「<<SP_type>>」=「太陽熱温水器(太陽熱給湯1)」

選択肢::
* 0度(水平) [規定値]
* 10度
* 20度
* 30度
* 40度
* 50度
* 60度
* 70度
* 80度
* 90度(鉛直)

[[SP_solar_system]]
==== ソーラーシステム(太陽熱給湯2)

表示条件::
「<<SP_type>>」=「ソーラーシステム(太陽熱給湯2)」

===== a. 面積の入力方法 [選択入力]

表示条件::
「<<SP_type>>」=「ソーラーシステム(太陽熱給湯2)」

説明::

====
太陽熱温水器の面積の定義は2種類あります。 +
有効集熱面積は、 ISO 9488「Solar energy - Vocabulary」の 8.6 節「aperture area」に規定される方法により算出する値です。
集熱部総面積又は集熱貯湯部総面積は、JIS A4111「太陽熱温水器」に規定されています。
====

選択肢::
* 集熱部面積又は集熱貯湯部総面積を入力する [規定値]
* 有効集熱面積を入力する

===== b. 集熱部面積又は集熱貯湯部総面積 [数値入力]

表示条件::
「a. 面積の入力方法」=「集熱部面積又は集熱貯湯部総面積を入力する」

入力規則::
最小値=0.0, 最大値=99.9, 小数点=1, 規定値=0.0, 単位=m^2^

===== c. 有効集熱面積 [数値入力]

表示条件::
「a. 面積の入力方法」=「有効集熱面積を入力する」

入力規則::
最小値=0.0, 最大値=99.9, 小数点=1, 規定値=0.0, 単位=m^2^

===== d. 集熱部の設置方位角 [選択入力]

表示条件::
「<<SP_type>>」=「ソーラーシステム(太陽熱給湯2)」

選択肢::
* 真南から東および西へ15度未満 [規定値]
* 真南から東へ15度以上45度未満
* 真南から東へ45度以上75度未満
* 真南から東へ75度以上105度未満
* 真南から東へ105度以上135度未満
* 真南から東へ135度以上165度未満
* 真南から東および西へ165度以上真北まで
* 真南から西へ135度以上165度未満
* 真南から西へ105度以上135度未満
* 真南から西へ75度以上105度未満
* 真南から西へ45度以上75度未満
* 真南から西へ15度以上45度未満

===== e. 集熱部の設置傾斜角 [選択入力]

表示条件::
「<<SP_type>>」=「ソーラーシステム(太陽熱給湯2)」

選択肢::
* 0度(水平) [規定値]
* 10度
* 20度
* 30度
* 40度
* 50度
* 60度
* 70度
* 80度
* 90度(鉛直)

===== f. 貯湯タンクの容量 [選択入力]

表示条件::
「<<SP_type>>」=「ソーラーシステム(太陽熱給湯2)」

選択肢::
* 100L以上150L未満
* 150L以上200L未満
* 200L以上300L未満 [規定値]
* 300L以上400L未満
* 400L以上
