== 日射熱取得・遮蔽計画

=== タブの下の表示項目

暖房目標レベル　A　（暖房エネルギー削減率B％程度） +
冷房目標レベル　C　（冷房エネルギー削減率D％程度） +
ηA~H~値 E (W/m^2^)/(W/m^2^) +
ηA~C~値 F (W/m^2^)/(W/m^2^)

=== タブの下の説明

見出し::
日射熱取得・遮蔽計画とは

説明::

====
日射熱制御とは、冬期において建物内に入る日射を上手に取得することにより、暖房エネルギー消費量の削減を実現することを目的とした技術と、夏期・中間期において建物内に入る日射を上手に遮蔽することにより、太陽熱の過度な流入を抑制し、冷房エネルギー消費量の削減と快適性の向上を実現することを目的とした技術です。
冬期には日射を取得し、夏期・中間期には日射を遮蔽するという相反する性能が求められるため、ブラインドやすだれ等の付属部材を活用するなど、上手に設計することが重要です。さらに、日射熱取得及び日射熱遮蔽性能に大きく影響を与える開口部においては、自然風利用や昼光利用を損なうことのないように計画することが大切です。
====
// 改修版テキスト

=== 環境条件

NOTE: <<GL_solar_heat_acquisition_location>> の内容を埋め込み

区域建蔽率 G% （立地：H型）

NOTE: 立地Hには、「郊外型の立地」「密集していない都市型の立地」「密集した都市型の立地」のいずれかの値をとる。区域建蔽率は、立地の種類に応じて定まる。(郊外型の立地：25%, 密集していない都市型の立地：35%, 密集した都市型の立地：50%)

=== 入力

[[SC_evaluation]]
==== 外皮性能の評価方法

説明::
====
外皮面積を計算する方法を選択します。当該住宅の外皮の部位の面積や長さを用いて計算する方法と、外皮の部位の面積や長さをひろわずに簡易的に計算する方法があります。
「当該住宅の外皮の部位の面積や長さを用いて計算する方法」を選択する場合は、別途、住宅の外皮計算を行って算出される平均日射熱取得率（ηA値）などを入力します。
「簡易計算法により外皮面積を算定する」を選択する場合は、各部位の日射熱取得率（η値）などを入力して日射熱取得・遮蔽性能を簡易的に算定する事ができます。その場合の住宅形状は一定で評価されますので、当該住宅の外皮性能の正確な値を用いる場合は「当該住宅の外皮の部位の面積や長さを用いて計算する方法」を選択してください。
====

===== a. 評価方法の選択 [選択入力]

NOTE: この項目は「断熱外皮計画」と共通である。簡易的にη値を計算する方法は、簡易的に計算する方法におけるU値の値に依存するため、「断熱外皮計画」「日射熱取得・遮蔽計画」のどちらか一方のみ「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する方法」が選択されることはない。

選択肢::
* 当該住宅のすべての外皮面積や長さを用いて評価する [規定値]
* 大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する

[[SC_input_solar_gain_performance]]
==== 外皮の日射熱取得・遮蔽性能の入力

表示条件::
「<<SC_evaluation>>」「a. 評価方法の選択」=「当該住宅のすべての外皮面積や長さを用いて評価する」

説明::
====
日射熱取得率（η値）は、入射する日射熱のうち室内側へ流入する熱の割合を表したもので、この値が小さいほど、日射遮蔽性能が高いことになります。
当該住宅の外皮の部位すべてについて、日射熱取得率（η値）や日除けの効果などを表す補正日射熱取得係数(f値)と面積を求め、平均日射取得係数（ηA値）を計算します。
====

===== a. 暖房期の平均日射熱取得率(η~AH~値) [数値入力]

表示条件::
「<<SC_evaluation>>」「a. 評価方法の選択」=「当該住宅のすべての外皮面積や長さを用いて評価する」
地域の区分が1～7地域

NOTE: 8地域は暖房期が無いため表示しない。

入力規則::
最小値=0.00, 最大値=9.99, 小数点=1位, +
規定値：地域によって異なる。 +
1地域 2.5, 2地域 2.3, 3地域 2.7, 4地域 3.7, 5地域 4.5, 6地域 4.3, 7地域 4.6, 8地域 -

===== b. 冷房期の平均日射熱取得率(η~AC~値) [数値入力]

表示条件::
「<<SC_evaluation>>」「a. 評価方法の選択」=「当該住宅のすべての外皮面積や長さを用いて評価する」

入力規則::
最小値=0.00, 最大値=9.99, 小数点=1位, +
規定値：地域によって異なる。 +
1地域 1.9, 2地域 1.9, 3地域 2.0, 4地域 2.7, 5地域 3.0, 6地域 2.8, 7地域 2.7, 8地域 3.2

===== c. 外皮の面積の合計(m^2^) [数値入力]

NOTE: この項目は「断熱外皮計画」と共通

表示条件::
「<<SC_evaluation>>」「a. 評価方法の選択」=「当該住宅のすべての外皮面積や長さを用いて評価する」

入力規則::
最小値=0.00, 最大値=5000.00, 小数点=2位, 規定値=307.51

[[SC_main_direction]]
==== 主開口の方位

表示条件::
「<<SC_evaluation>>」「a.評価方法の選択」=「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

説明::
====
主開口の方位を選択します。主開口の方位によって、日射の取得量がかわります。
====

===== a. 主開口の方位 [選択入力]

表示条件::
「<<SC_evaluation>>」「a.評価方法の選択」=「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

選択肢::
* 南 [規定値]
* 南西
* 西
* 北西
* 北
* 北東
* 東
* 南東

[[SC_window]]
==== 窓(透明な開口部)の日射熱取得性能

表示条件::
「<<SC_evaluation>>」「a. 評価方法の選択」=「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

説明::
====
窓・ドアなどの開口部には、熱・空気・光・眺望など屋内外をつなげる機能と同時に、建物外皮の一部としての断熱性や防犯性が要求されます。
開口部 の日射遮蔽対策が講じられていない場合には、夏期及び中間期において、建物室内の温度の上昇をまねき快適性が著しく損なわれるほか、冷房エネルギーの大幅な増加の原因となります。また、開口部の日射遮蔽によって冬期における暖房負荷が増加する作用のあることも考慮する必要があります。理想的には、夏期は日射熱取得率を低く、冬期には高くすることのできる工夫が必要といえます。
開口部の日射熱取得率(η値)は、ガラス、ブラインド等の日射遮蔽部材及び庇・軒等の各部位の対策の手厚さの程度によって決まります。
====

===== a. 入力する方法の選択 [選択入力]

表示条件::
「<<SC_evaluation>>」「a. 評価方法の選択」=「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

選択肢::
* 窓全体の日射熱取得率(η~d,H~値)を入力する [規定値]
* ガラス(グレージング)や建具、付属部材の種類を入力する

===== b. 窓の暖房期の日射熱取得率 [数値入力]

表示条件::
「a. 入力する方法の選択」=「窓全体の日射熱取得率(η~d,H~値)を入力する」

入力規則::
最小値=0.00, 最大値=0.99, 小数点=2位, 規定値=0.70

===== C. 窓の冷房期の日射熱取得率 [数値入力]

表示条件::
「a. 入力する方法の選択」=「窓全体の日射熱取得率(η~d,H~値)を入力する」

入力規則::
最小値=0.00, 最大値=0.99, 小数点=2位, 規定値=0.70

[[SC_window_spec_for_heating_season]]
==== 暖房期における窓の仕様

表示条件::
「<<SC_window>>」「a. 入力する方法の選択」=「ガラス(グレージング)や建具、付属部材の種類を入力する」

説明::
====
暖房期における窓の枠の種類・ガラスの種類・付属部材の種類・有効な日除けの有無を入力します。複数の仕様が考えられる場合には、日射熱の取得が最も小さい窓の仕様を入力します。
====

===== a. 枠の種類 [選択入力]

表示条件::
「<<SC_window>>」「a. 入力する方法の選択」=「ガラス(グレージング)や建具、付属部材の種類を入力する」

選択肢::
* 木製建具
* 樹脂製建具
* 木と金属の複合材料製建具
* 樹脂と金属の複合材料製建具
* 金属製熱遮断構造建具
* 金属製建具 [規定値]

===== b. ガラス(グレージング)の種類

表示条件::
「<<SC_window>>」「a. 入力する方法の選択」=「ガラス(グレージング)や建具、付属部材の種類を入力する」

選択肢::
* 2枚以上のガラス表面にLow-E膜を使用したLow-E三層複層ガラス(日射取得型)
* 2枚以上のガラス表面にLow-E膜を使用したLow-E三層複層ガラス(日射遮蔽型)
* Low-E三層複層ガラス(日射取得型)
* Low-E三層複層ガラス(日射遮蔽型)
* Low-E複層ガラス(日射取得型)
* Low-E複層ガラス(日射遮蔽型)
* 遮熱複層ガラス(熱線反射ガラス 1種)
* 遮熱複層ガラス(熱線反射ガラス 2種)
* 遮熱複層ガラス(熱線反射ガラス 3種)
* 遮熱複層ガラス(熱線吸収板ガラス 2種)
* 複層ガラス
* 単板ガラス2枚を組み合わせたもの
* 単板ガラス(熱線反射ガラス 1種)
* 単板ガラス(熱線反射ガラス 2種)
* 単板ガラス(熱線反射ガラス 3種)
* 単板ガラス(熱線吸収板ガラス 2種)
* 単板ガラス(その他) [規定値]

===== c. 付属部材の種類

表示条件::
「<<SC_window>>」「a. 入力する方法の選択」=「ガラス(グレージング)や建具、付属部材の種類を入力する」

選択肢::
* 付属部材を設置しない [規定値]
* 和障子を設置する
* 内付けブラインドを設置する
* 外付けブラインドを設置する

[[SC_window_spec_for_cooling_season]]
==== 冷房期における窓の仕様

NOTE: 選択項目・表示条件・選択肢・説明など、「暖房期における窓の仕様」と同じ

[[SC_indow_eaves_for_heating_season]]
==== 5) 窓(透明な開口部)の日除け

表示条件::
「<<SC_evaluation>>」「a.評価方法の選択」=「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== a. 選択入力：窓の日除け

表示条件::
「<<SC_evaluation>>」「a.評価方法の選択」=「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

説明::
====
有効なひさしの設置の有無を選択します。 +
ここで有効なひさしとは、「庇の出＞0.3×庇の根元と窓下端との距離」を満たすひさしのことを言います。([underline]#有効なひさし#) +
有効なひさしを設置しているとして評価する場合、上記の条件を満たすひさしがすべての窓に設けられている場合を条件とします。
====

選択肢::
* 有効なひさしを設置している [規定値]
* 有効なひさしが設置されていない
