# appveyor.yml
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install
  - git clone --depth 1 https://github.com/asciidoctor/asciidoctor-fopub
  - ps: $path = "$pwd\fonts"
  - ps: $shell = New-Object -ComObject Shell.Application
  - ps: $shell.Namespace($path).Items().InvokeVerbEx("Install")

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - java -version

test_script:
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% index.adoc --trace
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% spec.adoc --trace
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% CalculationSpec\CalculationSpec.adoc --trace
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% CalculationSpec\eesCalculationSpec.adoc --trace
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% CalculationSpec\JJJCalculationSpec.adoc --trace
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% -b docbook spec.adoc --trace
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% -b docbook CalculationSpec\CalculationSpec.adoc --trace
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% -b docbook CalculationSpec\eesCalculationSpec.adoc --trace
  - asciidoctor -r asciidoctor-diagram -a commit-id=%APPVEYOR_REPO_COMMIT% -b docbook CalculationSpec\JJJCalculationSpec.adoc --trace
  - cd asciidoctor-fopub
  - fopub ..\spec.xml -xsl ..\conf\docbook-config\fo-pdf.xsl
  - fopub ..\spec.xml -xsl ..\conf\docbook-config\fo-pdf.xsl
  - fopub ..\CalculationSpec\CalculationSpec.xml -xsl ..\conf\docbook-config\fo-pdf.xsl
  - fopub ..\CalculationSpec\eesCalculationSpec.xml -xsl ..\conf\docbook-config\fo-pdf.xsl
  - fopub ..\CalculationSpec\JJJCalculationSpec.xml -xsl ..\conf\docbook-config\fo-pdf.xsl
  - cd ..
  - mkdir dist
  - mkdir dist\images
  - mkdir dist\CalculationSpec
  - copy index.html dist\index.html
  - copy spec.html dist\spec.html
  - copy spec.pdf dist\spec.pdf
  - copy CalculationSpec\CalculationSpec.html dist\CalculationSpec\CalculationSpec.html
  - copy CalculationSpec\eesCalculationSpec.html dist\CalculationSpec\eesCalculationSpec.html
  - copy CalculationSpec\JJJCalculationSpec.html dist\CalculationSpec\JJJCalculationSpec.html
  - copy CalculationSpec\CalculationSpec.pdf dist\CalculationSpec.pdf
  - copy CalculationSpec\eesCalculationSpec.pdf dist\eesCalculationSpec.pdf
  - copy CalculationSpec\JJJCalculationSpec.pdf dist\JJJCalculationSpec.pdf
  - xcopy images dist\images\ /s /e

artifacts:
- path: dist
  name: document

deploy:
- provider: FTP
  host: waws-prod-hk1-001.ftp.azurewebsites.windows.net
  protocol: ftps
  username: jjjdoc\jjjdoc
  password:
    secure: G3QJ5qkuXlj46an5IH1+5A==
  folder: site\wwwroot
  application: document
