= 日射熱取得・遮蔽計画

== 1. タブの下の表示項目

|==========
暖房目標レベル　A　（暖房エネルギー削減率B％程度） +
冷房目標レベル　C　（冷房エネルギー削減率D％程度） +
ηA~H~値 E (W/m^2^)/(W/m^2^) +
ηA~C~値 F (W/m^2^)/(W/m^2^)
|==========

== 2. タブの下の説明

===== 見出し
日射熱取得・遮蔽計画とは

===== 説明

|==========
日射熱制御とは、冬期において建物内に入る日射を上手に取得することにより、暖房エネルギー消費量の削減を実現することを目的とした技術と、夏期・中間期において建物内に入る日射を上手に遮蔽することにより、太陽熱の過度な流入を抑制し、冷房エネルギー消費量の削減と快適性の向上を実現することを目的とした技術です。
冬期には日射を取得し、夏期・中間期には日射を遮蔽するという相反する性能が求められるため、ブラインドやすだれ等の付属部材を活用するなど、上手に設計することが重要です。さらに、日射熱取得及び日射熱遮蔽性能に大きく影響を与える開口部においては、自然風利用や昼光利用を損なうことのないように計画することが大切です。
|==========

// 改修版テキスト

== 3. 環境条件
|==========
区域建蔽率 G% （立地：H型）
|==========
立地Hには、「郊外型の立地」「密集していない都市型の立地」「密集した都市型の立地」のいずれかの値をとる。
区域建蔽率は、立地の種類に応じて、以下のように定まる。 +
- 郊外型の立地：25% +
- 密集していない都市型の立地：35% +
- 密集した都市型の立地：50%

== 4. 入力

=== 1) 外皮性能の評価方法

===== 表示条件
なし

===== 説明
|==========
外皮面積を計算する方法を選択します。当該住宅の外皮の部位の面積や長さを用いて計算する方法と、外皮の部位の面積や長さをひろわずに簡易的に計算する方法があります。
「当該住宅の外皮の部位の面積や長さを用いて計算する方法」を選択する場合は、別途、住宅の外皮計算を行って算出される平均日射熱取得率（ηA値）などを入力します。
「簡易計算法により外皮面積を算定する」を選択する場合は、各部位の日射熱取得率（η値）などを入力して日射熱取得・遮蔽性能を簡易的に算定する事ができます。その場合の住宅形状は一定で評価されますので、当該住宅の外皮性能の正確な値を用いる場合は「当該住宅の外皮の部位の面積や長さを用いて計算する方法」を選択してください。
|==========

==== a.  選択入力：評価方法の選択
※ この項目は「断熱外皮計画」と共通 +
※ 簡易的にη値を計算する方法は、簡易的に計算する方法におけるU値の値に依存するため、「断熱外皮計画」「日射熱取得・遮蔽計画」のどちらか一方のみ「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する方法」が選択されることはない。

===== 表示条件
なし

===== 選択肢
|==========
・当該住宅のすべての外皮面積や長さを用いて評価する(規定値) +
・大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する
|==========

=== 2) 外皮の日射熱取得・遮蔽性能の入力
===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「当該住宅のすべての外皮面積や長さを用いて評価する」

===== 説明
|==========
日射熱取得率（η値）は、入射する日射熱のうち室内側へ流入する熱の割合を表したもので、この値が小さいほど、日射遮蔽性能が高いことになります。
当該住宅の外皮の部位すべてについて、日射熱取得率（η値）や日除けの効果などを表す補正日射熱取得係数(f値)と面積を求め、平均日射取得係数（ηA値）を計算します。
|==========

==== a. 数値入力：暖房期の平均日射熱取得率（η~AH~値）

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「当該住宅のすべての外皮面積や長さを用いて評価する」
地域の区分が1～7地域（8地域は暖房期が無いため表示しない。）

===== 入力規則
最小値=0.00, 最大値=9.99, 小数点=1位, +
規定値：地域によって異なる。 +
1地域 2.5, 2地域 2.3, 3地域 2.7, 4地域 3.7, 5地域 4.5, 6地域 4.3, 7地域 4.6, 8地域 -

==== b. 数値入力：冷房期の平均日射熱取得率（η~AC~値）

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「当該住宅のすべての外皮面積や長さを用いて評価する」

===== 入力規則
最小値=0.00, 最大値=9.99, 小数点=1位, +
規定値：地域によって異なる。 +
1地域 1.9, 2地域 1.9, 3地域 2.0, 4地域 2.7, 5地域 3.0, 6地域 2.8, 7地域 2.7, 8地域 3.2

==== c. 数値入力：外皮の面積の合計（m^2^）
※ この項目は「断熱外皮計画」と共通

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「当該住宅のすべての外皮面積や長さを用いて評価する」

===== 入力規則
最小値=0.00, 最大値=5000.00, 小数点=2位, 規定値=307.51

=== 3) 主開口の方位

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 説明
|==========
主開口の方位を選択します。主開口の方位によって、日射の取得量がかわります。
|==========

==== a. 選択入力：主開口の方位

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 選択肢
|==========
・南(規定値) +
・南西 +
・西 +
・北西 +
・北 +
・北東 +
・東 +
・南東
|==========

=== 4) 窓(透明な開口部)の日射熱取得性能

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 説明
|==========
窓・ドアなどの開口部には、熱・空気・光・眺望など屋内外をつなげる機能と同時に、建物外皮の一部としての断熱性や防犯性が要求されます。
開口部 の日射遮蔽対策が講じられていない場合には、夏期及び中間期において、建物室内の温度の上昇をまねき快適性が著しく損なわれるほか、冷房エネルギーの大幅な増加の原因となります。また、開口部の日射遮蔽によって冬期における暖房負荷が増加する作用のあることも考慮する必要があります。理想的には、夏期は日射熱取得率を低く、冬期には高くすることのできる工夫が必要といえます。
開口部の日射熱取得率 （η値）は、ガラス、ブラインド等の日射遮蔽部材及び庇・軒等の各部位の対策の手厚さの程度によって決まります。
|==========

==== a. 数値入力：主たる方位の窓の暖房期の日射熱取得率

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 入力規則
最小値=0.00, 最大値=0.99, 小数点=2位, 規定値=0.70

==== b. 数値入力：主たる方位の窓の冷房期の日射熱取得率

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 入力規則
最小値=0.00, 最大値=0.99, 小数点=2位, 規定値=0.70

==== c. 数値入力：その他の方位の窓の暖房期の日射熱取得率

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 入力規則
最小値=0.00, 最大値=0.99, 小数点=2位, 規定値=0.70

==== d. 数値入力：その他の方位の窓の冷房期の日射熱取得率

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 入力規則
最小値=0.00, 最大値=0.99, 小数点=2位, 規定値=0.70

=== 5) 窓(透明な開口部)の日除け

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

==== a. 選択入力：主たる方位の窓の日除け

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 選択肢
|==========
・有効なひさしを設置している(規定値) +
・有効なひさしが設置されていない
|==========

==== b. 選択入力：その他の方位の窓の日除け

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 選択肢
|==========
・有効なひさしを設置している(規定値) +
・有効なひさしが設置されていない
|==========
