= コージェネレーション

== 1. タブの下の表示項目

目標レベル A (住宅全体のエネルギー削減率B%程度) +

== 2. タブ下の説明

===== 見出し
コージェネレーションとは

===== 説明

== 3. 環境条件
なし

== 4. 入力

=== 1) コージェネレーションの採用 [選択入力]

===== 選択肢
・採用しない +
・採用する

=== 2) コージェネレーションの方式 [選択入力]

===== 表示条件
「1) コージェネレーションの採用」=「採用する」

===== 選択肢
・PEFC(固体高分子形燃料電池)
・SOFC(固体酸化物形燃料電池)
・GEC(ガスエンジンコージェネレーション)

=== 3) PEFC(固体高分子形燃料電池)

===== 表示条件
「2) コージェネレーションの方式」=「PEFC(固体高分子形燃料電池)」

==== a. 評価の方法

===== 表示条件
「2) コージェネレーションの方式」=「PEFC(固体高分子形燃料電池)」

===== 選択肢
・デフォルト仕様を用いて評価する +
・カテゴリから選択して省エネ性能を評価する(2015年度以前の評価方法) +
・メーカー名や品番等を指定して評価する(2015年度以降の評価方法) +

==== b. カテゴリの選択 [選択入力]

===== 表示条件
「a. 評価の方法」=「カテゴリから選択して省エネ性能を評価する(2015年度以前の評価方法)」

===== 選択肢
・PEFC1 +
・PEFC2 +
・PEFC3 +
・PEFC4 +
・PEFC5 +
・PEFC6 +

==== c. 品番等 [テキスト入力]
「a. 評価の方法」=「メーカー名や品番等を指定して評価する(2015年度以降の評価方法)」

=== 4) SOFC(固体酸化物形燃料電池)

===== 表示条件
「2) コージェネレーションの方式」=「SOFC(固体酸化物形燃料電池)」

==== a. 評価の方法

===== 表示条件
「2) コージェネレーションの方式」=「SOFC(固体酸化物形燃料電池)」

===== 選択肢
・デフォルト仕様を用いて評価する +
・カテゴリから選択して省エネ性能を評価する(2015年度以前の評価方法) +
・メーカー名や品番等を指定して評価する(2015年度以降の評価方法) +

==== b. カテゴリの選択 [選択入力]

===== 表示条件
「a. 評価の方法」=「カテゴリから選択して省エネ性能を評価する(2015年度以前の評価方法)」

===== 選択肢
・SOFC1 +
・SOFC2 +

==== c. 品番等 [テキスト入力]
「a. 評価の方法」=「メーカー名や品番等を指定して評価する(2015年度以降の評価方法)」

=== 5) GEC(ガスエンジンコージェネレーション)

===== 表示条件
「2) コージェネレーションの方式」=「GEC(ガスエンジンコージェネレーション)」

==== a. 評価の方法

===== 表示条件
「2) コージェネレーションの方式」=「GEC(ガスエンジンコージェネレーション)」

===== 選択肢
・デフォルト仕様を用いて評価する +
・カテゴリから選択して省エネ性能を評価する

==== b. カテゴリの選択 [選択入力]

===== 表示条件
「a. 評価の方法」=「カテゴリから選択して省エネ性能を評価する」

===== 選択肢
・GEC1 +
・GEC2 +
