= 太陽光発電

== 1. タブの下の表示項目
なし

== 2. タブ下の説明

===== 見出し
太陽光発電

===== 説明
太陽光発電は、日中に自然エネルギーである太陽光で発電を行い、住宅内で消費する電力を自己生産するシステムです。夜間は通常どおり電力を購入する必要がありますが、日中の余剰電力は売電することができますので、トータルとして電力収支が改善されランニングコストを極めて低く抑えることが可能になります。

== 3. 環境条件
なし

== 4. 入力

=== 1) 太陽光発電の採用とパネルの枚数

==== a. 太陽光発電の採用 [選択入力]

===== 選択肢
・採用しない +
・採用する

==== b. 方位の異なるパネル [選択入力]

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「a. 太陽光発電の採用」=「採用する」

===== 選択肢
・1面 +
・2面 +
・3面 +
・4面 +

=== 2) パワーコンディショナー

==== a. 定格負荷効率の入力 [選択入力]

===== 選択肢
・入力しない (規定値)
・入力する

==== b. 定格負荷効率 [数値入力]

===== 入力規則
最小値=90.00, 最大値=99.99, 小数点=2, 規定値=92.8, 単位=%

=== 3) 方位の異なるパネルその1

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「1面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「2面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「3面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

==== a. 太陽電池アレイのシステム容量 [数値入力]

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「1面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「2面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「3面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

===== 入力規則
最小値=0.00, 最大値=99.99, 小数点=2, 規定値=2.00, 単位=kW

==== b. 太陽電池アレイの種類 [選択入力]

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「1面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「2面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「3面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

===== 選択肢
・結晶シリコン系太陽電池 +
・結晶シリコン系以外の太陽電池

==== c. 太陽電池アレイの設置方式 [選択入力]

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「1面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「2面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「3面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

===== 選択肢
・架台設置形 +
・屋根置き形 +
・その他

==== d. パネル設置方位の方位角 [選択入力]

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「1面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「2面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「3面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

===== 選択肢
・真南から東および西へ15度未満
・真南から東へ15度以上45度未満
・真南から東へ45度以上75度未満
・真南から東へ75度以上105度未満
・真南から東へ105度以上135度未満
・真南から東へ135度以上165度未満
・真南から東および西へ165度以上真北まで
・真南から西へ135度以上165度未満
・真南から西へ105度以上135度未満
・真南から西へ75度以上105度未満
・真南から西へ45度以上75度未満
・真南から西へ15度以上45度未満

==== e. パネル設置角度の傾斜角 [選択入力]

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「1面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「2面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「3面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

===== 選択肢
・0度(水平)
・10度
・20度
・30度
・40度
・50度
・60度
・70度
・80度
・90度(鉛直)

=== 4) 方位の異なるパネルその2

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「2面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「3面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

選択項目は、「方位の異なるパネルその1」と同じ

=== 5) 方位の異なるパネルその3

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「3面」又は
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

選択項目は、「方位の異なるパネルその1」と同じ

=== 6) 方位の異なるパネルその4

===== 表示条件
「1) 太陽光発電の採用とパネルの枚数」「b. 方位の異なるパネル」=「4面」

選択項目は、「方位の異なるパネルその1」と同じ




