= 断熱外皮計画

== 1. タブの下の表示項目
// とりあえず。なし。
// [表示]
// 暖房目標レベル　A　（暖房エネルギー削減率B％程度）　 入力方法　C　
// 冷房目標レベル　D　（冷房エネルギー削減率E％程度）　 入力方法　F　
// UA値　G W/㎡K　　Q値　H W/㎡K　　換気除くQ値　I W/㎡K
// ηA値　J　μ値　K

== 2. タブの下の説明

===== 見出し
断熱外皮計画とは

===== 説明
----
断熱外皮計画は、住宅の室内と室外との境界（外皮）における熱の出入りの抑制を目的としています。断熱化をはかった住宅は、無断熱の住宅に比べ、はるかに少ないエネルギーで冬期の室内温熱環境を快適にすることができます。
----
// 準寒冷地テキストp.128

== 3. 環境条件
// 項目なし

== 4. 入力

=== 1) 外皮性能の評価方法

===== 表示条件
なし

===== 説明
----
外皮面積を計算する方法を選択します。当該住宅の外皮の部位の面積や長さを用いて計算する方法と、外皮の部位の面積や長さをひろわずに簡易的に計算する方法があります。「当該住宅の外皮の部位の面積や長さを用いて計算する方法」を選択する場合は、別途、住宅の外皮計算を行って算出される外皮平均熱貫流率（UA値）などを入力します。「簡易計算法により外皮面積を算定する」を選択する場合は、各部位の熱貫流率（U値）と日射熱取得率（η値）などを入力して断熱外皮性能および日射熱取得・遮蔽性能を簡易的に算定する事ができます。その場合の住宅形状は一定で評価されますので、当該住宅の外皮性能の正確な値を用いる場合は「当該住宅の外皮の部位の面積や長さを用いて計算する方法」を選択してください。
----

==== (1) 選択入力：評価方法の選択

===== 表示条件
なし

===== 選択肢
----
・当該住宅のすべての外皮面積や長さを用いて評価する(規定値)
・大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する
----

=== 2) 外皮の断熱性能の入力
===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「当該住宅のすべての外皮面積や長さを用いて評価する」

===== 説明
----
当該住宅の外皮の部位すべてについて、熱貫流率（U値）と面積または線熱貫流率（ψ値）と長さを求め、外皮平均熱貫流率（UA値）を計算します。
----

==== (1) 数値入力：外皮平均熱貫流率（U~A~値）（W/m^2^K）

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「当該住宅のすべての外皮面積や長さを用いて評価する」

==== 入力規則
最小値=0.00, 最大値=9.99, 小数点=2位, +
規定値：地域によって異なる。 +
1地域0.46, 2地域0.46, 3地域0.56, 4地域0.75, 5地域0.87, 6地域0.87, 7地域0.87, 8地域2.14

==== (2)数値入力：外皮の面積の合計（m^2^）

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「当該住宅のすべての外皮面積や長さを用いて評価する」

===== 入力規則
最小値=0.00, 最大値=5000.00, 小数点=2位, 規定値=307.51

=== 3) 床または基礎の断熱方法

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 説明
----
床または基礎の断熱方法を選択します。ただし、玄関土間や浴室下部などのみに部分的に基礎断熱部分が発生する場合は床断熱を選択してください。
----

==== (1) 選択入力：床または基礎の断熱方法

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 選択肢
----
・床断熱を行う(規定値)
・基礎断熱を行う
・床断熱と基礎断熱の併用を行う
----

=== 4) 主開口の方位

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 説明
----
主開口の方位を選択します。主開口の方位によって、日射の取得量がかわります。
----

==== (1) 選択入力：主開口の方位

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 選択肢
----
・南(規定値)
・南西
・西
・北西
・北
・北東
・東
・南東
----

=== 5) 外壁の断熱性能

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 説明
外壁の断熱性能を入力します。入力方法は熱貫流率（U値）を直接入力する方法と、断熱の仕方や断熱材の種類・厚さなどを選択して入力する方法があります。

==== (1) 選択入力：入力する方法の選択

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 選択肢
----
・熱貫流率（U値）を直接入力する(規定値)
・断熱の仕方や断熱材の種類・厚さなどを選択して入力する
----

==== (2) 数値入力：熱貫流率（U値）（W/m^2^K）

===== 表示条件
「5)外壁の断熱性能(1)入力する方法の選択」＝「熱貫流率（U値）を直接入力する」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値=0.000

==== (3) 選択入力：外気側の状態

===== 表示条件
「5)外壁の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
外気側の状態（通気層の有無）によって、外気側の熱伝達抵抗が変わります。
----

===== 選択肢
----
・外気に直接接する(規定値)
・外気以外（通気層等）に接する
----

==== (4) 選択入力：断熱の方法

===== 表示条件
「5)外壁の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
外壁の断熱の方法を選択してください。断熱の方法によって熱橋の面積の割合が変わります。
----

===== 選択肢
----
・軸組構法において柱や間柱間に断熱する場合(規定値)
・軸組構法において柱や間柱間に断熱し付加断熱する場合
・枠組壁工法においてたて枠間に断熱する場合
・枠組壁工法においてたて枠間に断熱し付加断熱する場合
・軸組み構法および枠組壁工法において外張断熱する場合
----

==== (5) 数値入力：断熱材の熱伝導率（λ値）（W/mK）

===== 表示条件
「5)外壁の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
断熱材の熱伝導率（λ値）を入力します。メーカーから公表している値（試験値）を入力するか、断熱材の種類から値を選択して入力します。
----
「表：断熱材の種類と熱伝導率（λ値）」のPDFをリンクさせる。

===== 入力規則
最小値=0.000, 最大値=1.000, 小数点=3位, 規定値=0.000

==== (6)  数値入力：断熱材の厚さ（m）

===== 表示条件
「5)外壁の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.10

==== (7) 数値入力：断熱材（付加断熱）の熱伝導率（λ値）（W/mK）

===== 表示条件
「5)外壁の断熱性能(3)断熱の方法」＝「軸組構法において柱や間柱間に断熱し付加断熱する場合」or「枠組壁工法においてたて枠間に断熱し付加断熱する場合」

===== 説明
----
断熱材の熱伝導率（λ値）を入力します。メーカーから公表している値（試験値）を入力するか、断熱材の種類から値を選択して入力します。
----
「表：断熱材の種類と熱伝導率（λ値）」のPDFをリンクさせる。

===== 入力規則
最小値=0.000, 最大値=1.000, 小数点=3位, 規定値=0.000

==== (8) 数値入力：断熱材（付加断熱）の厚さ（m）

===== 表示条件
「5)外壁の断熱性能(3)断熱の方法」＝「軸組構法において柱や間柱間に断熱し付加断熱する場合」or「枠組壁工法においてたて枠間に断熱し付加断熱する場合」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.10

=== 6) 屋根または天井の断熱性能

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 説明
----
屋根または天井の断熱性能を入力します。入力方法は熱貫流率（U値）を直接入力する方法と、断熱の仕方や断熱材の種類・厚さなどを選択して入力する方法があります。
----

==== (1) 選択入力：入力する方法の選択

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 選択肢
----
・熱貫流率（U値）を直接入力する(規定値)
・断熱の仕方や断熱材の種類・厚さなどを選択して入力する
----

==== (2) 数値入力：熱貫流率（U値）（W/m^2^K）

===== 表示条件
「6)屋根または天井の断熱性能(1)入力する方法の選択」＝「熱貫流率（U値）を直接入力する」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値=0.000

==== (3) 選択入力：外気側の状態

===== 表示条件
「6)屋根または天井の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
外気側の状態（通気層の有無）によって、外気側の熱伝達抵抗が変わります。
----

===== 選択肢
----
・外気側に直接接する(規定値)
・外気以外（通気層や小屋裏等）に接する
----

==== (4) 選択入力：断熱の方法

===== 表示条件
「6)屋根または天井の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
屋根断熱や天井断熱の方法を選択してください。断熱の方法によって熱橋の面積の割合が変わります。
----

===== 選択肢
----
・天井断熱工法において梁や桁間に断熱する場合(規定値)
・天井断熱工法において天井一面に断熱する場合
・屋根断熱工法においてたるき間に断熱する場合
・屋根断熱工法において外張断熱する場合
・屋根断熱工法においてたるき間に断熱し付加断熱する場合
----

==== (5) 数値入力：断熱材の熱伝導率（λ値）（W/mK）

===== 表示条件
「6)屋根または天井の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
断熱材の熱伝導率（λ値）を入力します。メーカーから公表している値（試験値）を入力するか、断熱材の種類から値を選択して入力します。
----
「表：断熱材の種類と熱伝導率（λ値）」のPDFをリンクさせる。

===== 入力規則
最小値=0.000, 最大値=1.000, 小数点=3位, 規定値=0.000

==== (6) 数値入力：断熱材の厚さ（m）

===== 表示条件
「6)屋根または天井の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.10

==== (7) 数値入力：断熱材（付加断熱）の熱伝導率（λ値）（W/mK）

===== 表示条件
「6)屋根または天井の断熱性能(3)断熱の方法」＝「屋根断熱工法においてたるき間に断熱し付加断熱する場合」

===== 説明
----
断熱材の熱伝導率（λ値）を入力します。メーカーから公表している値（試験値）を入力するか、断熱材の種類から値を選択して入力します。
----
「表：断熱材の種類と熱伝導率（λ値）」のPDFをリンクさせる。

===== 入力規則
最小値=0.000, 最大値=1.000, 小数点=3位, 規定値=0.000

==== (8) 数値入力：断熱材（付加断熱）の厚さ（m）

===== 表示条件
「6)屋根または天井の断熱性能(3)断熱の方法」＝「屋根断熱工法においてたるき間に断熱し付加断熱する場合」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.10

=== 7) 床の断熱性能

===== 表示条件
「3)床または基礎の断熱方法(1)床または基礎の断熱方法」＝「床断熱を行う」or「床断熱と基礎断熱の併用を行う」

===== 説明
----
床の断熱性能を入力します。入力方法は熱貫流率（U値）を直接入力する方法と、断熱の仕方や断熱材の種類・厚さなどを選択して入力する方法があります。
----

==== (1) 選択入力：入力する方法の選択

===== 表示条件
「3)床または基礎の断熱方法(1)床または基礎の断熱方法」＝「床断熱を行う」or「床断熱と基礎断熱の併用を行う」

===== 選択肢
----
・熱貫流率（U値）を直接入力する(規定値)
・断熱の仕方や断熱材の種類・厚さなどを選択して入力する
----

==== (2) 数値入力：熱貫流率（U値）（W/m^2^K）

===== 表示条件
「7)床の断熱性能(1)入力する方法の選択」＝「熱貫流率（U値）を直接入力する」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値=0.000

==== (3) 選択入力：外気側の状態

===== 表示条件
「7)床の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
外気側の状態（床裏に面するか又は外気に直接面するかどうか）によって、外気側の熱伝達抵抗が変わります。
----

===== 選択肢
----
・外気側に直接接する(規定値)
・外気以外（床裏等）に接する
----

==== (4)  選択入力：断熱の方法

===== 表示条件
「7)床の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
床の断熱の方法を選択してください。断熱の方法によって熱橋の面積の割合が変わります。
----

===== 選択肢
----
・軸組構法において床梁工法を採用し根太間に断熱する場合(規定値)
・軸組構法において束立大引工法を採用し根太間に断熱する場合
・軸組構法において束立大引工法を採用し大引間に断熱する場合
・軸組構法において束立大引工法を採用し根太間および大引間に断熱する場合
・軸組構法において剛床工法を採用する場合
・軸組構法において床梁土台同面工法を採用し根太間に断熱する場合
・枠組工法において根太間に断熱する場合
----

==== (5) 数値入力：断熱材の熱伝導率（λ値）（W/mK）

===== 表示条件
「7)床の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
断熱材の熱伝導率（λ値）を入力します。メーカーから公表している値（試験値）を入力するか、断熱材の種類から値を選択して入力します。
----
「表：断熱材の種類と熱伝導率（λ値）」のPDFをリンクさせる。

===== 入力規則
最小値=0.000, 最大値=1.000, 小数点=3位, 規定値=0.000

==== (6) 数値入力：断熱材の厚さ（m）

===== 表示条件
「7)床の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.10

==== (7) 数値入力：断熱材（2層目）の熱伝導率（λ値）（W/mK）

===== 表示条件
「7)床の断熱性能(3)断熱の方法」＝「軸組構法において束立大引工法を採用し根太間および大引間に断熱する場合」

===== 説明
----
断熱材の熱伝導率（λ値）を入力します。メーカーから公表している値（試験値）を入力するか、断熱材の種類から値を選択して入力します。
----
「表：断熱材の種類と熱伝導率（λ値）」のPDFをリンクさせる。

===== 入力規則
最小値=0.000, 最大値=1.000, 小数点=3位, 規定値=0.000

==== (8) 数値入力：断熱材（2層目）の厚さ（m）

===== 表示条件
「7)床の断熱性能(3)断熱の方法」＝「軸組構法において束立大引工法を採用し根太間および大引間に断熱する場合」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.10

=== 8) 土間床等の周囲部の断熱性能

===== 表示条件
「3)床または基礎の断熱方法(1)床または基礎の断熱方法」＝「基礎断熱を行う」or「床断熱と基礎断熱の併用を行う」

===== 説明
----
土間床等の外周部の断熱性能を入力します。入力方法は線熱貫流率（ψ値）を直接入力する方法と、断熱の仕方や断熱材の種類・厚さなどを選択して入力する方法があります。
----

==== (1) 選択入力：入力する方法の選択

===== 表示条件
「3)床または基礎の断熱方法①床または基礎の断熱方法」＝「基礎断熱を行う」or「床断熱と基礎断熱の併用を行う」

===== 選択肢
----
・線熱貫流率（ψ値）を直接入力する(規定値)
・断熱の仕方や断熱材の種類・厚さなどを選択して入力する
----

==== (2) 数値入力：線熱貫流率（ψ値）（W/mK）

===== 表示条件
「8)土間床等の周囲部の断熱性能(1)入力する方法の選択」＝「線熱貫流率（ψ値）を直接入力する」

===== 入力規則
最小値=0.000, 最大値=1.800, 小数点=3位, 規定値=0.000

==== (3) 選択入力：基礎等の深さ

===== 表示条件
「8)土間床等の周囲部の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 説明
----
基礎等の深さとは、地盤面からの基礎等の底盤等上端の深さを言います。詳しくはこちら。
----
「図：基礎等の深さ」のPDFをリンクさせる。

===== 説明
----
基礎等のまわりの断熱材の位置や長さの取り方についてはこちらをご覧ください。
----
「図：基礎等のまわりの断熱材の位置や長さ」のPDFをリンクさせる。

===== 選択肢
----
・1m以内(規定値)
・1mを超える
----

==== (4) 数値入力：基礎等の立ち上がり部分の室外側に設置した断熱材の熱抵抗（R1）（m^2^K/W）

===== 表示条件
「8)土間床等の周囲部の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値=0.600

==== (5) 数値入力：基礎等の底盤部分等の室内側に設置した断熱材の熱抵抗（R2）（m^2^K/W）

===== 表示条件
「8)土間床等の周囲部の断熱性能③基礎等の深さ」＝「1m以内」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値=0.600

==== (6) 数値入力：基礎等の底盤部分等の室外側に設置した断熱材の熱抵抗（R3）（m^2^K/W）

===== 表示条件
「8)土間床等の周囲部の断熱性能③基礎等の深さ」＝「1m以内」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値：0.600

==== (7) 数値入力：基礎等の立ち上がり部分の室内側に設置した断熱材の熱抵抗（R4）（m^2^K/W）

===== 表示条件
「8)土間床等の周囲部の断熱性能(1)入力する方法の選択」＝「断熱の仕方や断熱材の種類・厚さなどを選択して入力する」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値=0.600

==== (8) 数値入力：地盤面からの基礎等の寸法（H1）（m）

===== 表示条件
「8)土間床等の周囲部の断熱性能(3)基礎等の深さ」＝「1m以内」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.00

==== (9) 数値入力：地盤面からの基礎等の底盤等上端までの寸法（H2）（m）

===== 表示条件
「8)土間床等の周囲部の断熱性能(3)基礎等の深さ」＝「1m以内」

===== 説明
----
地盤面より上方を正の値、下方を負の値とします。
----

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.00

==== (10) 数値入力：地盤面より下の基礎等の立ち上がり部分の室外側の断熱材の施工深さ（W1）（m）

===== 表示条件
「8)土間床等の周囲部の断熱性能(3)基礎等の深さ」＝「1m以内」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.00

==== (11) 数値入力：基礎等の底盤部分等の室内側に設置した断熱材の水平方向の折返し寸法（W2）（m）

===== 表示条件
「8)土間床等の周囲部の断熱性能(3)基礎等の深さ」＝「1m以内」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.00

==== (12) 数値入力：基礎等の底盤部分等の室外側に設置した断熱材の水平方向の折返し寸法（W3）（m）

===== 表示条件
「8)土間床等の周囲部の断熱性能(3)基礎等の深さ」＝「1m以内」

===== 入力規則
最小値=0.00, 最大値=5.00, 小数点=2位, 規定値=0.00

=== 9) 開口部の断熱性能

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 説明
----
窓・ドアなどの開口部には、熱・空気・光・眺望など屋内外をつなげる機能と同時に、建物外皮の一部としての断熱性や防犯性が要求されます。このうち断熱性については、建物外皮の中で弱点となりやすい部位ですので、適切な性能のあるものを選択することが大切です。入力方法は熱貫流率（U値）を直接入力する方法と、ガラス（グレージング）の熱貫流率（U値）を入力し建具の種類を選択する方法があります。「入力方法は熱貫流率（U値）を直接入力する方法」は、従来省エネ基準などで使用されていた方法で、枠やガラスの種類などによって表から選択する方法と、JIS A 4710, JIS A1492, JIS A 2102のように試験や計算による方法があります。
----
「図：窓等の大部分がガラスで構成される開口部（一重構造の建具）の熱貫流率」のPDFをリンクさせる。

==== (1) 選択入力：入力する方法の選択

===== 表示条件
「1)外皮性能の評価方法(1)評価方法の選択」＝「大まかな住宅形状から簡易的に求めた外皮面積や長さを用いて評価する」

===== 選択肢
----
・窓全体の熱貫流率（Uw値）を入力する(規定値)
・ガラス（グレージング）の熱貫流率（Ug値）と建具の種類を入力する
----

==== (2) 数値入力：窓全体の熱貫流率（UW値）（W/m^2^K）

===== 表示条件
「9)開口部の断熱性能(1)入力する方法の選択」＝「窓全体の熱貫流率（Uw値）を入力する」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値=0.000

==== (3) 選択入力：枠の種類

===== 表示条件
「9)開口部の断熱性能(1)入力する方法の選択」＝「ガラス（グレージング）の熱貫流率（Ug値）と建具の種類を入力する」

===== 選択肢
----
・木製建具
・樹脂製建具
・木と金属の複合材料製建具
・樹脂と金属の複合材料製建具
・金属製熱遮断構造建具
・金属製建具(規定値)
----

==== (4) 数値入力：ガラス（グレージング）の熱貫流率（Ug値）

===== 表示条件
「9)開口部の断熱性能(1)入力する方法の選択」＝「ガラス（グレージング）の熱貫流率（Ug値）と建具の種類を入力する」

===== 入力規則
最小値=0.000, 最大値=15.000, 小数点=3位, 規定値=0.000
