= 蓄熱の利用

== 1. タブの下の表示項目

|==========
目標レベル A (暖房エネルギー削減率B%程度)
|==========

== 2. タブの下の説明

===== 見出し
蓄熱の利用とは

===== 説明
|==========
蓄熱の利用は、冬期における暖房エネルギー消費の削減に有効な技術です。地域の気候特性や立地などの条件を勘案して、集熱、開口部の断熱保温、蓄熱の３つの建築的な手法をバランスよく設計することが重要となります。
|==========

== 3. 環境条件
項目なし

== 4. 入力

=== 1) 蓄熱の利用

===== 表示条件
なし

===== 説明
|==========
蓄熱は、室温を安定して保つのに効果のある技術で、日中は熱を吸収して室のオーバーヒートを防ぎ、夜間は吸収・蓄熱した熱を放出して室温の低下を防ぎます。また、夏期においては逆に夜間の冷気を蓄え(蓄冷)、日中の冷却効果をもたらします。蓄熱部位の熱容量が大きいほど、室温の変動が抑えられ安定します。暖房時にも同様ですが、熱容量が大きい材料を用いると、部屋は暖まりにくくなりますが、一旦暖まると冷めにくくする効果が現れます。 +
熱容量は次式で求められます。 +

熱容量(kJ/K)　=　蓄熱部位の容積(m^3^) × 蓄熱材の容積比熱(kJ/m^3^K) +

蓄熱部位は、有効厚さが設定されており、位置や面積、厚さ等の設計上の留意点を加味した計画が望まれます。

容積比熱と有効厚さは、こちら（コメント：ＰＤＦ）を参照してください。

蓄熱部位の要件 +
蓄熱部位の熱容量 +
170 (kJ/Km^2^)程度以上の熱容量の増加が見込まれる材料を蓄熱部位に用いること +
参考：土塗壁および土間床を蓄熱部位とした場合の木造住宅算定例
|==========

|==========
【ポップアップ：蓄熱部位】 +
蓄熱部位に用いる材料には、次の特性をもつものが適しています。 +
・熱容量(容積比熱)が大きいこと。 +
・熱が伝わりやすいこと。 +
・表面からの熱の吸収・放散がすみやかに行われること。 +
蓄熱に有効な建築部位の対象には、床、外壁、間仕切り壁、天井があげられます。生活のために家具・什器など多くのものが室内に持ちこまれますが、これらの熱容量も蓄熱効果があります。
|==========

|==========
【ポップアップ：設計上の留意点】 +
蓄熱の効果を確保するために、設計上次の事項に留意することが大切です。 +
1. 蓄熱部位の位置 +
・蓄熱の効果は、蓄熱部位に直接日射が当たり、日射受熱量が大きいほど顕著になりますが、日射が直接当たらない部位でも蓄熱効果を見込むことができます。 +
2. 蓄熱部位の面積 +
・蓄熱部位の面積は広いほど蓄熱効果は大きくなります。広い面積に簿く熱を蓄える設計とすることが望まれます。 +
3. 蓄熱部位の厚さ +
・蓄熱部位の厚さについては、材料の有効厚さ以上では蓄熱性能が変わらないことを意識して計画すること、例えば石やコンクリートなどを用いる場合、その厚さを15cm～20cm以内にすることが有効です。
|==========

|==========
【ポップアップ：有効厚さ】 +
材料には蓄熱部位として計上できる「有効厚さ」が設定されています。材料の容積算定時において、材料の厚さが有効厚さ以上の場合は、有効厚さまでのみを計上することができます。これは、有効厚さ以上の材料の蓄熱効果は小さいことを意味しています。熱が伝わりやすい材料ほど、有効厚さは大きくなります。
|==========

==== a. 主たる居室
===== 表示条件
なし

===== 選択肢
|==========
・	利用する +
・	利用しない
|==========

==== b.	その他の居室
===== 表示条件
なし

===== 選択肢
|==========
・	利用する +
・	利用しない
|==========

==== c.	非居室
===== 表示条件
なし

===== 選択肢
|==========
・	利用する +
・	利用しない
|==========
