:stem: latexmath

==== 付録B 蓄熱の利用

本付録は、本計算方法における暖房負荷の計算に当たり、「蓄熱の利用あり」の要件を規定する。

「蓄熱の利用あり」と評価するためには、蓄熱部位の熱容量が当該住戸の床面積当たり170kJ/(m^2^K)以上の熱容量の増加が見込まれる材料を蓄熱部位に用いていることが条件となる。蓄熱部位とは、蓄熱の利用に有効な熱容量を持つ部位をいい、天井、床(断熱区画内の床も含む)、壁(外気に接する壁及び間仕切壁)及び界壁・界床を対象とする。蓄熱部位の熱容量は式(1)により表される。

// ees
ifndef::JJJ[]
ifndef::official[====]
ifndef::official[ees]

latexmath:[
\begin{equation}
C = \sum_i{ ( \sum_j{ ( (c \rho)_{i,j} \times l_{i,j} ) \times A_i } ) } \div A_A
\tag{1}
\end{equation}
]

ここで、

[horizontal]
latexmath:[C]:: :住戸の床面積当たりの蓄熱部位の熱容量 (kJ/(m^2^･K))
latexmath:[(c \rho)_{i,j}]:: :蓄熱部位 latexmath:[i] の層 latexmath:[j] の容積比熱 (kJ/(m^3^･K))
latexmath:[l_{i,j}]:: :蓄熱部位latexmath:[i]の層 latexmath:[j] の有効蓄熱厚さ (m)
latexmath:[A_i]:: :蓄熱部位 latexmath:[i] の表面積 (m^2^）
latexmath:[A_A]:: :床面積の合計 (m^2^)

ifndef::official[====]
endif::JJJ[]

// JJJ
ifndef::ees[]
ifndef::official[====]
ifndef::official[JJJ]

latexmath:[
\begin{equation}
C = \sum_i{ ( \sum_j{ ( (c \rho)_{i,j} \times l_{i,j} ) \times A_i } ) } \div A_f
\tag{i}
\end{equation}
]

ここで、

[horizontal]
latexmath:[C]:: :住戸の床面積当たりの蓄熱部位の熱容量 (kJ/(m^2^･K))
latexmath:[(c \rho)_{i,j}]:: :蓄熱部位 latexmath:[i] の層 latexmath:[j] の容積比熱 (kJ/(m^3^･K))
latexmath:[l_{i,j}]:: :蓄熱部位latexmath:[i]の層 latexmath:[j] の有効蓄熱厚さ (m)
latexmath:[A_i]:: :蓄熱部位 latexmath:[i] の表面積 (m^2^）
latexmath:[A_f]:: :「主たる居室」、「その他の居室」又は「非居室」の床面積の合計 (m^2^)

ifndef::official[====]
endif::ees[]

である。蓄熱部位 latexmath:[i] の層 latexmath:[j] の容積比熱 latexmath:[(c \rho)_{i,j}] 及び蓄熱部位 latexmath:[i] の層 latexmath:[j] の有効蓄熱厚さ latexmath:[l_{i,j}] は、表B.1によるものとする。

蓄熱部位とみなせる範囲は、最も室内側の材料を含めて断熱材又は密閉されていない空気層の間に位置する材料であり、界床・界壁等の場合は、壁厚の半分の厚さまでを見込むことができる。この限りにおいて、部材が複数ある場合(各部材を層という。)、各層すべて蓄熱部位とみなすことができる。ただし、層ごとに、表B.1で示す有効蓄熱厚さを超えて計上することはできない。

[caption="表B.1 "]
.容積比熱及び有効蓄熱厚さ
[cols="4"]
|====
2+^| 材料名
^| 容積比熱 latexmath:[c \rho]

(J/(L･K))

^| 有効蓄熱厚さ latexmath:[l]

(m)


.7+^| セメント

コンクリート

レンガ

^| セメント・モルタル ^| 1600 ^| 0.23
^| コンクリート ^| 2000 ^| 0.2
^| 軽量コンクリート(軽量1種) ^| 1900 ^| 0.11
^| 軽量コンクリート(軽量2種) ^| 1600 ^| 0.08
^| 押出成形セメント板 ^| 2100 ^| 0.05
^| 軽量気泡コンクリートパネル(ALCパネル) ^| 660 ^| 0.07
^| れんが ^| 1499 ^| 0.11

.4+^| 金属類

^| 銅 ^| 3200 ^| 制限なし
^| アルミニウム ^| 2400 ^| 制限なし
^| 鋼 ^| 3600 ^| 制限なし
^| ステンレス鋼 ^| 3500 ^| 制限なし

^| ガラス等 ^| ガラス ^| 1900 ^| 0.13

.4+^| 木質系

木質繊維系

^| 天然木材 ^| 520 ^| 0.06
^| 合板 ^| 720 ^| 0.06
^| ハードファイバーボード(ハードボード) ^| 1230 ^| 0.03
^| パーティクルボード ^| 720 ^| 0.05

.2+^| せっこう

^| せっこうボード ^| 830 ^| 0.07
^| せっこうプラスター ^| 1600 ^| 0.09

.2+^| 壁

^| 漆喰 ^| 1400 ^| 0.13
^| 土壁 ^| 1100 ^| 0.16

.3+^| 床材

^| 畳床 ^| 290 ^| 0.13
^| タイル ^| 2000 ^| 0.16
^| ビニル系床材 ^| 1500 ^| 0.03

|====
