:stem: latexmath

==== 付録C 方位係数

// ees
ifndef::JJJ[]
ifndef::official[]
[caption=]
.ees
====
endif::official[]

外皮の部位の暖房期の方位係数は表1に定める値とする。外皮の部位の冷房期の方位係数は、表2に定める値とする。

ifndef::official[====]
endif::JJJ[]

// JJJ
ifndef::ees[]
ifndef::official[]
[caption=]
.JJJ
====
endif::official[]

外皮の部位の方位係数は、式(i)により表される。

latexmath:[
\begin{equation}
\nu_{H,i} = \nu_{H,i,opn} \times c_{\nu,H,i}
\tag{ia}
\end{equation}
]

latexmath:[
\begin{equation}
\nu_{C,i} = \nu_{C,i,opn} \times c_{\nu,C,i}
\tag{ib}
\end{equation}
]

ここで、

[horizontal]
latexmath:[\nu_{H,i}]:: :方位 latexmath:[i] に面した暖房期の方位係数
latexmath:[\nu_{H,i,opn}]:: :方位 latexmath:[i] に面した暖房期の隣棟を考慮しない方位係数
latexmath:[c_{\nu,H,i}]:: :方位 latexmath:[i] に面した暖房期の隣棟を考慮した方位係数の低減係数
latexmath:[\nu_{C,i}]:: :方位 latexmath:[i] に面した冷房期の方位係数
latexmath:[\nu_{C,i,opn}]:: :方位 latexmath:[i] に面した冷房期の隣棟を考慮しない方位係数
latexmath:[c_{\nu,C,i}]:: :方位 latexmath:[i] に面した冷房期の隣棟を考慮した方位係数の低減係数

である。

方位 latexmath:[i] に面した暖房期の隣棟を考慮した方位係数の低減係数 latexmath:[c_{\nu,H,i}] 及び方位 latexmath:[i] に面した冷房期の隣棟を考慮しない方位係数 latexmath:[c_{\nu,C,i}] は、隣棟の影響を考慮しない場合はともに暖房期・冷房期ともに latexmath:[1.0] とし、隣棟の影響を考慮する場合は式(ii)により表される。

latexmath:[
\begin{equation}
c_{\nu,H,i} =　\frac{ 1 }{ ( 1 + 1 / ( a_H \cdot d^2 + b_H \cdot d ) ) }
\tag{iia}
\end{equation}
]

latexmath:[
\begin{equation}
c_{\nu,C,i} =　\frac{ 1 }{ ( 1 + 1 / ( a_C \cdot d^2 + b_C \cdot d ) ) }
\tag{iib}
\end{equation}
]

ここで、

[horizontal]
latexmath:[d]:: :隣棟との距離 (m)

である。式中の係数 latexmath:[a_H] , latexmath:[b_H] , latexmath:[a_C] , latexmath:[b_C] は表Iにより定義される。

[caption=表I]
.式(iia)及び式(iib)注の係数
|====
.2+^.^| 方位 2+^| 暖房期 2+^| 冷房期
^| 係数a ^| 係数b ^| 係数a ^| 係数b
^| 南   ^| 0.0436 ^| 0.0000 ^| 0.0307 ^| 0.1933
^| 南西 ^| 0.0368 ^| 0.0156 ^| 0.0464 ^| 0.0583
^| 西   ^| 0.0295 ^| 0.0528 ^| 0.0255 ^| 0.0747
^| 北西 ^| 0.0286 ^| 0.1035 ^| 0.0249 ^| 0.0947
^| 北   ^| 0.0297 ^| 0.1168 ^| 0.0153 ^| 0.1371
^| 北東 ^| 0.0284 ^| 0.1055 ^| 0.0250 ^| 0.0972
^| 東   ^| 0.0302 ^| 0.0490 ^| 0.0259 ^| 0.0773
^| 南東 ^| 0.0361 ^| 0.0138 ^| 0.0456 ^| 0.0625
|====

隣棟との距離 latexmath:[d] は、グロス建蔽率 latexmath:[r_{bc}] から式(iii)により表される。

latexmath:[
\begin{equation}
d = 67.1 \cdot \exp ^ { ( -6.05 \cdot r_{bc}) }
\tag{iii}
\end{equation}
]

グロス建蔽率 latexmath:[r_{bc}] は、 立地に応じて表IIに定める値とする。

[caption=表II]
.グロス建蔽率
|====
^| 立地 ^| 値
| 立地1 : 密集している市街地 ^| 0.25
| 立地2 : 密集していない市街地 ^| 0.35
| 立地3 : 郊外 ^| 0.5
|====

方位 latexmath:[i] に面した暖房期の隣棟を考慮しない方位係数 latexmath:[\nu_{H,i,opn}] 及び方位 latexmath:[i] に面した冷房期の隣棟を考慮しない方位係数 latexmath:[\nu_{C,i,opn}] はそれぞれ表1及び表2に定める値とする。

ifndef::official[====]
endif::ees[]

外皮の部位の方位は、当該部位の屋外に向かう法線の水平投影線の方位を、それぞれ北、北東、東、南東、南、南西、西、北西の各方位（真北方向を基準とした直交方位軸を設定し、その直交方位軸と±22.5度で交わる線により区分される範囲）と、上面、下面に振り分けた値とする。

屋根の面する方位については、勾配の有無に関わらず上面に面するものとして取扱うこととする。

界壁及び界床の方位係数はlatexmath:[0]とする。

[caption=表1 ]
.暖房期の方位係数
[cols="9*^"]
|====
.2+^.^| 方位 8+^| 地域の区分
| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
| 上面 7+| 1.0 .10+| －
| 北 | 0.260 | 0.263 | 0.284 | 0.256 | 0.238 | 0.261 | 0.227
| 北東 | 0.333 | 0.341 | 0.348 | 0.330 | 0.310 | 0.325 | 0.281
| 東 | 0.564 | 0.554 | 0.540 | 0.531 | 0.568 | 0.579 | 0.543
| 南東 | 0.823 | 0.766 | 0.751 | 0.724 | 0.846 | 0.833 | 0.843
| 南 | 0.935 | 0.856 | 0.851 | 0.815 | 0.983 | 0.936 | 1.023
| 南西 | 0.790 | 0.753 | 0.750 | 0.723 | 0.815 | 0.763 | 0.848
| 西 | 0.535 | 0.544 | 0.542 | 0.527 | 0.538 | 0.523 | 0.548
| 北西 | 0.325 | 0.341 | 0.351 | 0.326 | 0.297 | 0.317 | 0.284
| 下面 7+| 0.0
|====

[caption=表2]
.冷房期の方位係数
[cols="9*^"]
|====
.2+^.^| 方位 8+^| 地域の区分
| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
| 上面 8+| 1.0
| 北 | 0.329 | 0.341 | 0.335 | 0.322 | 0.373 | 0.341 | 0.307 | 0.325
| 北東 | 0.430 | 0.412 | 0.390 | 0.426 | 0.437 | 0.431 | 0.415 | 0.414
| 東 | 0.545 | 0.503 | 0.468 | 0.518 | 0.500 | 0.512 | 0.509 | 0.515
| 南東 | 0.560 | 0.527 | 0.487 | 0.508 | 0.500 | 0.498 | 0.490 | 0.528
| 南 | 0.502 | 0.507 | 0.476 | 0.437 | 0.472 | 0.434 | 0.412 | 0.480
| 南西 | 0.526 | 0.548 | 0.550 | 0.481 | 0.520 | 0.491 | 0.479 | 0.517
| 西 | 0.508 | 0.529 | 0.553 | 0.481 | 0.518 | 0.504 | 0.495 | 0.505
| 北西 | 0.411 | 0.428 | 0.447 | 0.401 | 0.442 | 0.427 | 0.406 | 0.411
| 下面 8+| 0.0
|====

// JJJ
ifndef::ees[]
ifndef::official[]
[caption=]
.JJJ
====
endif::official[]

NOTE: 表1及び表2のタイトルは、「暖房期の方位係数」「冷房期の方位係数」であるが、それぞれ「暖房期の隣棟を考慮しない方位係数」「冷房期の隣棟を考慮しない方位係数」と読み替える。

ifndef::official[====]
endif::ees[]
